### ISSUE TITLE
running this image deleted all my images

### ISSUE THREAD

**Issue by lalyos** [rancher/sherdock#50] opened 2015-06-22 07:06 UTC
I was keen to see sherlock in action:

```
docker run -d -v /var/lib/docker:/var/lib/docker -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 rancher/sherdock
```

than port 8080 was showing an empty page, so i looked into the logs, and i got a heart attack:

```
[restful] 2015/06/22 06:56:42 log.go:30: [restful/swagger] listing is available at http://localhost:8080/apidocs.json
2015/06/22 06:56:42 start listening on localhost:8080
[restful] 2015/06/22 06:56:42 log.go:30: [restful/swagger] http://localhost:8080/apidocs/ is mapped to folder /Users/emicklei/xProjects/swagger-ui/dist
Pulling: ubuntu:latest
2015/06/22 06:56:43 Image 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55 matches regexp /busybox:latest/ to keep
2015/06/22 06:56:43 Image b87155bee962c0971aad177e7d4b98bfe9d13058108e80f202c93853234c2385 matches regexp /ubuntu:latest/ to keep
2015/06/22 06:56:43 Image d0955f21bf24f5bfffd32d2d0bb669d0564701c271bc3dfc64cfc5adfdec2d07 matches regexp /ubuntu:latest/ to keep
2015/06/22 06:56:43 Image 8cee90767cfea242efcaa19f922b7ed9c82c5db07a025185a8f93400fdcc269d matches regexp /busybox:latest/ to keep
2015/06/22 06:56:43 Image 9f44e6683ab0c53561b2bb3803d70e37d33c269a96435a4a25d78c3ed915ffc8 has children
2015/06/22 06:56:43 Image 1356dd669eb0b4d9ebc54f8839f6fe2dcec7767faf2ad6283f296cef7f28a519 has children
...
2015/06/22 06:56:43 Deleting image with image id 0f5d35f437a7e00a1d502b51928bbe45781273bd7affa1322682cae2ebeb3dcc [docker:simple]
2015/06/22 06:56:43 Deleting image with image id bb4b40e958fc97e800d0f97b32e49eeb4f5c327e58861a105ecb262eb4e54dec [docker-dev:master]
2015/06/22 06:56:44 Deleting image with image id bdd816919ed451ab2ba7fe290e14ab47cc606538ad80d831712d45943c4faefd [<none>:<none>]
2015/06/22 06:56:46 Deleting image with image id b5f28def6aae6d699ee581957ebbe0c1b919d893560d994a528e9b02414ec0e4 [<none>:<none>]
2015/06/22 06:56:54 Deleting image with image id 88cc5691d85295a39b274bf7f4b2f6189ab67c7083fc9de7cb3da7864af98568 [entrykit:latest]
2015/06/22 06:56:55 Deleting image with image id fd9bdc9a23ad516cee44c67e8901f91585c6f498a94cc67777c30c693fbc5cec [octopress:latest]
2015/06/22 06:56:56 Deleting image with image id 60b1fea19b6f4f17eb5d6fea576fe07e81a2293d22bb2344c446a7c00896d917 [<none>:<none>]
2015/06/22 06:56:56 Deleting image with image id b9876653d77cd1a4dd1a635f0ff8135a46cc0d079e965a4f3d4075db2902059c [<none>:<none>]
2015/06/22 06:56:58 Deleting image with image id aa3bff9c94e34e6526cebd2e140db9a06b289e47ef357e67534615ad7c2f2cf1 [docs-base:master]
2015/06/22 06:56:59 Deleting image with image id f4b4bd0dccb731b07fa2104381112f9763aa05fba4062dc6e1678eb93f1d8ffd [delme:latest]
2015/06/22 06:57:00 Deleting image with image id 38c06f9801d054778d2c5e99dcee4e63cdfab4915f6219d238297eda4398ea8b [elasticsearch:latest]
2015/06/22 06:57:04 Deleting image with image id 90b45c2f8696b7f4e5ba470daf5f4d038413f147fb01d4a229fd7482616aacf3 [logstash:latest]
2015/06/22 06:57:07 Deleting image with image id f97864eaa6ac0f62b274f14963f7f14be6685553a4b38930690f4efcc80c463b [logspout:dev]
2015/06/22 06:57:10 Deleting image with image id 95a8cde4b40e468d35b438d3ce1f652428e44bc1538b78c23bcc5c678ef3847e [openwrt-x86-generic-rootfs:latest]
2015/06/22 06:57:11 Deleting image with image id 76b9533e2bfb5e4d1d4d9a0d67ee115c73e2d07edfc9cdb984d4510f1f339b35 [ehazlett/interlock:latest]
2015/06/22 06:57:13 Deleting image with image id 7c3225aacf8a859712a1010ffc6f803e2245d3a9785090f00f7f0be6ac344a9b [gliderlabs/dockerhub-tag:0.1.7]
```

**Comment by ankushagarwal** [comment] 2015-06-22 07:17
This is a duplicate of #48

**Closed as completed** 2015-06-22 08:05 UTC

**Comment by ibuildthecloud** [comment] 2015-06-22 12:32
@lalyos I'm so sorry.  Terribly bad judgement on our part at 4am to set the default to GC everything.  I just changed it so that it will GC nothing by default.  You must configure it first.

**Comment by lalyos** [comment] 2015-06-22 12:36
No problem, i am aware of the meaning of cutting edge :D 

I've procrastinated cleaning up my images for month, so actually it helped me ;)
